### ISSUE TITLE
iOS crashes when invoking KommunicateFlutterPlugin.buildConversation

### ISSUE THREAD

**Issue by mbtodorov** [Kommunicate-io/Kommunicate-Flutter-Plugin#90]
Hello 👋 

We are using the kommunicate SDK. We've been having issues with crashes in our iOS production application for a while. Its impacted 110 sessions for the past 14 days in our app. We noticed that the release notes in the latest version of the SDK, `1.7.0`, included a 'fixed crashes' items. We assumed this might address the crashes we are having. 

<img width="604" alt="image" src="https://github.com/Kommunicate-io/Kommunicate-Flutter-Plugin/assets/25320807/69de128a-c679-434c-b90a-3d4578c06243">

However, even after upgrading to your latest version, the crashes still persist

<img width="775" alt="image" src="https://github.com/Kommunicate-io/Kommunicate-Flutter-Plugin/assets/25320807/5bfe00c9-a4c5-4796-a674-7c3cc9e38ac3">

I appreciate I haven't given any useful information around reproducing the issue. This is because we cant consistently reproduce it, there seem to be no clear steps. Let me know if I can provide any other helpful logs or other information. Any updates around this would be much appreciated!

Here is the entry for `kommunicate_sdk` from `pubspec.lock`:
```yml
  kommunicate_flutter:
    dependency: transitive
    description:
      name: kommunicate_flutter
      sha256: "915931eeec6e5abf5f450cda2be378c7d106e8e90bbc3501fda20bffbeecf05b"
      url: "https://pub.dev"
    source: hosted
    version: "1.7.0"
```
Here are all kommunicate-related entries from `Podfile.lock`:

```
  - Kommunicate (6.9.9):
    - KommunicateChatUI-iOS-SDK (~> 1.1.6)
  - kommunicate_flutter (0.0.1):
    - Flutter
    - Kommunicate (~> 6.9.2)
  - KommunicateChatUI-iOS-SDK (1.1.6):
    - KommunicateChatUI-iOS-SDK/Complete (= 1.1.6)
  - KommunicateChatUI-iOS-SDK/Complete (1.1.6):
    - iOSDropDown
    - Kingfisher (~> 7.6.2)
    - KommunicateChatUI-iOS-SDK/RichMessageKit
    - KommunicateCore-iOS-SDK (~> 1.1.1)
    - SwipeCellKit (~> 2.7.1)
    - ZendeskChatProvidersSDK (~> 3.0.0)
  - KommunicateChatUI-iOS-SDK/RichMessageKit (1.1.6)
  - KommunicateCore-iOS-SDK (1.1.1)
```
